//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int id_ap { get; set; }
        public Nullable<int> id_kt { get; set; }
        public Nullable<int> id_dep { get; set; }
        public Nullable<int> count_kt { get; set; }
    }
}
