//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Changes
    {
        public int Id { get; set; }
        public string Changer_name { get; set; }
        public string Changer_surname { get; set; }
        public string Change_date { get; set; }
        public string Change { get; set; }
    }
}
