//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.KancTovari = new HashSet<KancTovari>();
        }
    
        public int id_dep { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<KancTovari> KancTovari { get; set; }
    }
}
